[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "iprad"
version = "0.0.1"
description = "Powerful open-source IP checking tool"
authors = [
    {name = "deltaaa00", email = "deltaaa.crypto@proton.me"}
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "click>=8.1.0",
    "requests>=2.31.0",
    "rich>=13.0.0",
    "python-whois>=0.8.0",
    "icmplib>=3.0.4",
    "python-dotenv>=0.9.9",
    "psutil>=6.0.0",
]

[project.scripts]
iprad = "iprad.cli:main"

[tool.setuptools.packages.find]
where = ["."]